word1 = " Potato "

print("strip() '%s'" % word1)
print("'%s'" % word1.strip())
print()
print("lower() '%s'" % word1)
print("'%s'" % word1.lower())
print()
print("upper() '%s'" % word1)
print("'%s'" % word1.upper())
print()
print("islower() '%s'" % word1)
print("%s" % word1.islower())
print()
print("replace() '%s'" % word1)
print("'%s'" % word1.replace('o','a'))
print()
print("'abc' + 'def'")
print('abc' + 'def')
print()
print("'123' + str(4)")
print('123' + str(4))
print()
print("','.join(['butter','milk','banana'])")
print(','.join(['butter','milk','banana']))
print()
print("'butter,milk,banana'.split(',')")
print('butter,milk,banana'.split(','))
print()
print("'@' in 'myEmail@mail.com'")
print('@' in 'myEmail@mail.com')
